openapi: '3.0.0'
info:
  description: Meetup API Node
  version: '1.0'
  title: Meetup API Node
servers:
- url: http://localhost:3000/
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /remarks:
    get:
      summary: Busca um Remark
      description: Busca um Remark
      responses:
        '200':
          description: successful operation
